enemies, tiles and towers
Tesser3kt/gevo-tower-defense pull request #5
Opened 2023-02-22 16:16 UTC by jachymneumiprogramovat

folders for enemies with their types and basic functionality. same for towers and tiles. towers need to add fire function after the general config is done

2023-02-22 16:16 UTC, jachymneumiprogramovat commented
amogus

2023-02-23 08:12 UTC, Tesser3kt requested changes
Jeste par chybek v TowerObject.

2023-02-23 08:12 UTC, Tesser3kt commented on game_objects/towers/tower_object.py
> +        self.last_fired=time.clock_gettime()
time.clock_gettime potrebuje jako parametr konkretni objekt hodin. Pouzij time.time().

2023-02-23 08:12 UTC, Tesser3kt commented on game_objects/towers/tower_object.py
> +        if self.last_fired-self.reload_time<=0:
Tohle nebude fungovat. Ty ukladas last_fired jako konkretni cas. Abys dostal pocet sekund od posledniho vystrelu, musis spocitat time.time() - last_fired.

2023-02-23 14:00 UTC, jachymneumiprogramovat commented
Už jsem to oboje opravil

2023-02-28 11:58 UTC, merged